version: "3"

services:
  app:
    build: .
    volumes:
      - ./app:/usr/src/app
    environment:
      APP_DATABASE_USER: rails_dev
      APP_DATABASE_PASSWORD: password
    links: 
      - db
    command: bash -c "yarn install && 
          bundle install --path vendor/bundle &&
          bundle exec rails db:create && 
          bundle exec rails db:migrate &&
          yarn install &&
          rm -f tmp/pids/server.pid &&
          bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: rails_dev
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      